# Generated by Django 3.2.5 on 2021-07-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('init', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cammodels',
            name='camPic',
            field=models.ImageField(default='CamaraPics/04.jpg', upload_to='CamaraPics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profileImag',
            field=models.ImageField(default='ProfilePics/07.jpg', upload_to='ProfilePics/'),
        ),
    ]
